//! Wall-clock benchmark + cache-roundtrip tests for blue-noise generation.
//! `cargo test --release --test test_blue_noise_bench -- --include-ignored --nocapture`

use std::time::Instant;

#[path = "../src/blue_noise.rs"]
mod blue_noise;

#[test]
#[ignore]
fn bench_blue_noise_32_cubed() {
    let start = Instant::now();
    let bytes = blue_noise::generate([32, 32, 32], blue_noise::DEFAULT_SEED);
    let elapsed = start.elapsed();
    println!(
        "BlueNoise 32x32x32: {} bytes in {:?} ({:.2}s)",
        bytes.len(),
        elapsed,
        elapsed.as_secs_f64()
    );
    assert_eq!(bytes.len(), 32 * 32 * 32);
}

#[test]
#[ignore]
fn bench_blue_noise_load_or_generate_cache_hit_is_fast() {
    let path = std::env::temp_dir().join("ces_bn_bench_32.bin");
    let _ = std::fs::remove_file(&path);

    let t0 = Instant::now();
    let a = blue_noise::load_or_generate(&path, [32, 32, 32], blue_noise::DEFAULT_SEED);
    let cold = t0.elapsed();
    println!("Cold (no cache): {:.2}s", cold.as_secs_f64());

    let t0 = Instant::now();
    let b = blue_noise::load_or_generate(&path, [32, 32, 32], blue_noise::DEFAULT_SEED);
    let warm = t0.elapsed();
    println!("Warm (from cache): {:.4}s", warm.as_secs_f64());

    assert_eq!(a, b, "cached bytes must match generated bytes");
    assert!(
        warm.as_millis() < 200,
        "cache hit should be <200ms, got {:?}",
        warm
    );
    let _ = std::fs::remove_file(&path);
}

#[test]
#[ignore]
fn bench_blue_noise_64_cubed() {
    let start = Instant::now();
    let bytes = blue_noise::generate([64, 64, 64], blue_noise::DEFAULT_SEED);
    let elapsed = start.elapsed();
    println!(
        "BlueNoise 64x64x64: {} bytes in {:?} ({:.2}s)",
        bytes.len(),
        elapsed,
        elapsed.as_secs_f64()
    );
    assert_eq!(bytes.len(), 64 * 64 * 64);
}
